# Generated by Django 4.2.6 on 2024-01-21 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeepData',
            fields=[
                ('idDeep', models.AutoField(primary_key=True, serialize=False)),
                ('precision', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MachineData',
            fields=[
                ('idMachien', models.AutoField(primary_key=True, serialize=False)),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='schoolYear',
            fields=[
                ('idScholYear', models.AutoField(primary_key=True, serialize=False)),
                ('nameYear', models.CharField(blank=True, max_length=100, null=True)),
                ('id_year', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('identification', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='school_year',
            field=models.ManyToManyField(related_name='students', through='dashboard.StudentSchoolYear', to='dashboard.schoolyear'),
        ),
        migrations.CreateModel(
            name='ResultDataStudent',
            fields=[
                ('idDataStudentResult', models.AutoField(primary_key=True, serialize=False)),
                ('deserta', models.CharField(blank=True, max_length=300, null=True)),
                ('lstm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cnn', models.DecimalField(decimal_places=2, max_digits=5)),
                ('identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.student')),
            ],
        ),
        migrations.CreateModel(
            name='DataStudent',
            fields=[
                ('idDataStudent', models.AutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=300)),
                ('modality', models.CharField(max_length=300)),
                ('cycle', models.IntegerField()),
                ('qualification', models.DecimalField(decimal_places=2, max_digits=5)),
                ('courseName', models.CharField(max_length=300)),
                ('program', models.CharField(max_length=300)),
                ('region', models.CharField(max_length=300)),
                ('zone', models.CharField(max_length=300)),
                ('centerSchool', models.CharField(max_length=300)),
                ('studentType', models.CharField(max_length=300)),
                ('identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.student')),
                ('nameYear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.schoolyear')),
            ],
        ),
    ]
